### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by fujiaixin09** [ando-khachatryan/HiDDeN#20]
Hello! I'm running main.py There was an error in the file, but I couldn't find a solution

“”Running validation for epoch 1/200
Traceback (most recent call last):
  File "F:/fu/HiDDeN-master/main.py", line 147, in <module>
    main()
  File "F:/fu/HiDDeN-master/main.py", line 143, in main
    train(model, device, hidden_config, train_options, this_run_folder, tb_logger)
  File "F:\fu\HiDDeN-master\train.py", line 88, in train
    os.path.join(this_run_folder, 'images'), resize_to=saved_images_size)
  File "F:\fu\HiDDeN-master\utils.py", line 58, in save_images
    torchvision.utils.save_image(stacked_images, filename, original_images.shape[0], normalize=False)
  File "F:\fu\StegaStamp\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "F:\fu\StegaStamp\venv\lib\site-packages\torchvision\utils.py", line 135, in save_image
    im.save(fp, format=format)
  File "F:\fu\StegaStamp\venv\lib\site-packages\PIL\Image.py", line 1978, in save
    if format.upper() not in SAVE:
AttributeError: 'int' object has no attribute 'upper'

Process finished with exit code 1
“”

**Comment by fujiaixin09** [comment]
It's solved! There is no error in changing pytorch from 1.8 to 1.4.

**Comment by HongguLiu** [comment]
Are there any other solutions?

**Comment by ashitamo** [comment]
In util.py line 57,change this.
`torchvision.utils.save_image(stacked_images, filename,original_images.shape[0] ,normalize=False)`
`torchvision.utils.save_image(stacked_images, filename)`
