### ISSUE TITLE
Help!The version of torch used in the paper！

### ISSUE THREAD

**Issue by shdn0217** [ando-khachatryan/HiDDeN#30]
Running validation for epoch 1/300
Traceback (most recent call last):
  File "main.py", line 147, in <module>
    main()
  File "main.py", line 143, in main
    train(model, device, hidden_config, train_options, this_run_folder, tb_logger)
  File "/content/HiDDeN/train.py", line 85, in train
    utils.save_images(image.cpu()[:images_to_save, :, :, :],
  File "/content/HiDDeN/utils.py", line 57, in save_images
    torchvision.utils.save_image(stacked_images, filename, original_images.shape[0], normalize=False)
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torchvision/utils.py", line 728, in save_image
    im.save(fp, format=str(format))
  File "/usr/local/lib/python3.8/dist-packages/PIL/Image.py", line 2123, in save
    save_handler = SAVE[format.upper()]
KeyError: '8'

When we reproduce the experiment, we found a lot of errors caused by our difference from your Torch version.we  want to know which version of Torch you used in paper, Appreciate it.

**Comment by ando-khachatryan** [comment]
I am not the author of the paper, there is a link to the paper and their repo which was in Lua+Torch, NOT PyTorch.
This repo was tested with PyTorch 1.0.
